name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Service containers to run with this job
    services:
      neo4j:
        image: neo4j:5.21.0
        env:
          NEO4J_AUTH: neo4j/testpassword
        ports:
          - 7687:7687
        # Docker Hub rate limiting can be an issue, this is a basic health check
        options: >-
          --health-cmd "wget --no-verbose --tries=5 --spider localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests (offline)
      run: pytest -m "not online" --cov=src --cov-report=xml

    - name: Run online tests
      env:
        # The host is the name of the service container
        NEO4J_URI: bolt://localhost:7687
        NEO4J_USERNAME: neo4j
        NEO4J_PASSWORD: testpassword
        # Use default ollama settings for tests
        LLM_PROVIDER: ollama
        OLLAMA_BASE_URL: http://mock-ollama:11434
      run: pytest -m "online"
